StylesPath = styles

MinAlertLevel = suggestion

Vocab = NorthEndMakers

# Add styles that focus on concise and clear communication.
Packages = Microsoft, write-good

[*.{md}]
BasedOnStyles = Vale, Microsoft, write-good

# Ignore Jekyll templates
TokenIgnores = \
  (\{\{[^}]+\}\}), \
  (\{%[^%]+%\})

# Ignore Jekyll frontmatter
BlockIgnores = (?s)^---.*?---

Disable = GenderBias.Steward
